import { defineType, defineField } from "sanity";

export default defineType({
  name: "contactPage",
  title: "Contact Page",
  type: "object",
  groups: [
    { name: "content", title: "Page Content", default: true },
    { name: "sidebar", title: "Sidebar Info" },
    { name: "form", title: "Form Settings" },
  ],
  fields: [
    defineField({
      name: "sectionLabel",
      title: "Section Label",
      type: "string",
      description: "Small label above the page heading (e.g. Get in Touch)",
      group: "content",
    }),
    defineField({
      name: "heading",
      title: "Heading",
      type: "string",
      description: "Main heading on the contact page",
      group: "content",
    }),
    defineField({
      name: "introText",
      title: "Intro Text",
      type: "text",
      description: "Paragraph of text below the heading",
      group: "content",
    }),
    defineField({
      name: "location",
      title: "Location",
      type: "string",
      description: "Your location shown in the contact sidebar (e.g. Los Angeles, CA). Leave blank to hide this section.",
      group: "sidebar",
    }),
    defineField({
      name: "availability",
      title: "Availability",
      type: "string",
      description: "Current availability status (e.g. Available for bookings). Leave blank to hide this section.",
      group: "sidebar",
    }),
    defineField({
      name: "quote",
      title: "Quote",
      type: "string",
      description: "Inspirational quote displayed on the contact page. Leave blank to hide this section.",
      group: "sidebar",
    }),
    defineField({
      name: "contactInfoHeading",
      title: "Contact Info Heading",
      type: "string",
      description: "Heading for the contact information sidebar",
      group: "sidebar",
    }),
    defineField({
      name: "emailLabel",
      title: "Email Label",
      type: "string",
      description: "Label next to the email address in the sidebar",
      group: "sidebar",
    }),
    defineField({
      name: "locationLabel",
      title: "Location Label",
      type: "string",
      description: "Label next to the location in the sidebar",
      group: "sidebar",
    }),
    defineField({
      name: "availabilityLabel",
      title: "Availability Label",
      type: "string",
      description: "Label next to the availability status",
      group: "sidebar",
    }),
    defineField({
      name: "socialLabel",
      title: "Social Label",
      type: "string",
      description: "Label above the social links in the sidebar",
      group: "sidebar",
    }),
    defineField({
      name: "formLabels",
      title: "Form Labels",
      type: "object",
      description: "Labels displayed above each form field (the bold text visitors see above the input)",
      group: "form",
      fields: [
        defineField({ name: "name", title: "Name Label", type: "string" }),
        defineField({ name: "email", title: "Email Label", type: "string" }),
        defineField({ name: "projectType", title: "Project Type Label", type: "string" }),
        defineField({ name: "message", title: "Message Label", type: "string" }),
        defineField({ name: "submitButton", title: "Submit Button Text", type: "string" }),
      ],
    }),
    defineField({
      name: "formPlaceholders",
      title: "Form Placeholders",
      type: "object",
      description: "Gray helper text shown inside empty form fields (disappears when the visitor starts typing)",
      group: "form",
      fields: [
        defineField({ name: "name", title: "Name Placeholder", type: "string" }),
        defineField({ name: "email", title: "Email Placeholder", type: "string" }),
        defineField({ name: "projectType", title: "Project Type Placeholder", type: "string" }),
        defineField({ name: "message", title: "Message Placeholder", type: "string" }),
      ],
    }),
    defineField({
      name: "projectTypes",
      title: "Project Types",
      type: "array",
      of: [{ type: "string" }],
      description: "Options in the project type dropdown (e.g. E-commerce, Campaign, Branded Content)",
      group: "form",
    }),
    defineField({
      name: "successMessage",
      title: "Success Message",
      type: "string",
      description: "Message shown after a successful form submission (e.g. \"Thank you! I'll get back to you soon.\")",
      group: "form",
    }),
    defineField({
      name: "errorMessage",
      title: "Error Message",
      type: "string",
      description: "Message shown when the form fails to submit (e.g. \"Something went wrong. Please try again or email me directly.\")",
      group: "form",
    }),
  ],
});
